[tool.poetry]
name = "MultiObjectiveSurrogateOptimization"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
miv_simulator = { git = "https://github.com/GazzolaLab/MiV-Simulator.git", branch = "feature/mechanism-handling" }
dmosopt = { git = "https://github.com/iraikov/dmosopt.git", branch = "main" }
machinable = "^4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
